const test=require('node:test'),assert=require('node:assert/strict');
const core=require('../tienda/js/store-config-core.js'),catalog=require('../tienda/js/catalogo.js');
const base=catalog.originalProducts;
test('configuración vacía conserva IDs, precios, stock y rutas de todos los productos',()=>assert.deepEqual(core.apply(base,core.blank()),base));
test('editar precio y stock no muta el original ni afecta otras prendas del mismo diseño',()=>{const c=core.blank();c.products[17]={price:480,stock:{S:0,M:3,L:5},description:'Estampado de banda',leadTime:'Consultar'};const out=core.apply(base,c);assert.equal(out.find(p=>p.id===17).price,480);assert.equal(out.find(p=>p.id===17).stock.S,0);assert.equal(base.find(p=>p.id===17).price,450);assert.deepEqual(out.find(p=>p.id===1017),base.find(p=>p.id===1017));});
test('se agregan productos y categorías sin sobrescribir IDs anteriores',()=>{const c=core.blank();c.categories.deportes='Deportes';c.newProducts.push({id:4000,name:'Edición deportiva',price:500,garment:'camiseta',category:'deportes',img:'img/products/deporte-1.webp',stock:{S:2},published:false});const out=core.apply(base,c);assert.equal(out.length,base.length+1);assert.equal(out.at(-1).published,false);assert.equal(out.at(-1).garmentName,'Camiseta');assert.throws(()=>core.apply([...base,{id:4000}],c),/repetido/);});
test('configuraciones defectuosas se rechazan sin modificar los datos de entrada',()=>{for(const p of [{price:-1},{stock:{S:-2}},{name:'<img>'},{images:['https://otro/s.jpg']},{category:'inexistente'}]){const c=core.blank();c.products[17]=p;assert.throws(()=>core.apply(base,c));}assert.throws(()=>core.validate({...core.blank(),sizeGuides:[]}));assert.equal(base.find(p=>p.id===17).price,450);});
test('tallas duplicadas o incompletas no se publican como guía confirmada',()=>{const c=core.blank();c.sizeGuides.camiseta=[{size:'M',widthCm:50,lengthCm:70}];assert.equal(core.validate(c),true);c.sizeGuides.camiseta.push({size:'M',widthCm:51,lengthCm:71});assert.throws(()=>core.validate(c));c.sizeGuides.camiseta=[{size:'S',widthCm:0,lengthCm:70}];assert.throws(()=>core.validate(c));});
test('los dos nuevos temas se pueden publicar desde la configuración sin cambiar otros productos',()=>{for(const [id,topic]of [[45,'arte-tipografia'],[47,'deportes']]){const c=core.blank();c.products[id]={name:'Diseño confirmado',subcategory:topic,published:true,stock:{M:3}};const out=core.apply(base,c);assert.equal(out.find(p=>p.id===id).subcategory,topic);assert.equal(out.find(p=>p.id===id).published,true);assert.equal(out.find(p=>p.id===id).stock.M,3);assert.deepEqual(out.find(p=>p.id===1017),base.find(p=>p.id===1017));}});
