(() => {
'use strict';const core=MomotusStoreConfigCore,$=id=>document.getElementById(id),initial=JSON.parse(JSON.stringify(MomotusCatalog.settings)),key='momotus-store-admin-draft';let data=initial;const status=text=>$('admin-status').textContent=text;
try{const saved=localStorage.getItem(key);if(saved){const parsed=JSON.parse(saved);core.validate(parsed);data=parsed;}}catch{status('No se pudo recuperar el borrador. Se conserva la configuración publicada.');}
data={...core.blank(),...data};const categories=()=>({...{fauna:'Fauna Nica',anime:'Anime',urbano:'Urbano',games:'Games',unica:'Únicas'},...data.categories});
const all=()=>core.apply(MomotusCatalog.originalProducts,data);let active=null;
function commit(next,message){core.validate(next);core.apply(MomotusCatalog.originalProducts,next);data=next;try{localStorage.setItem(key,JSON.stringify(data));status(message+' · Borrador guardado.');}catch{status(message+' · No se pudo guardar en este navegador; descargá un respaldo.');}}
function options(){for(const id of ['admin-category','new-category']){$(id).replaceChildren(...Object.entries(categories()).map(([key,label])=>new Option(label,key)));}}
function loadProduct(id){active=all().find(p=>p.id===Number(id));if(!active)return;$('admin-name').value=active.baseName;$('admin-main-image').value=active.img;$('admin-price').value=active.price;$('admin-category').value=active.category;$('admin-topic').value=active.subcategory||'streetwear';$('admin-topic').disabled=active.category!=='urbano';for(const size of ['S','M','L'])$('admin-stock-'+size).value=active.stock[size]||0;for(const [id,key]of [['admin-description','description'],['admin-lead','leadTime']])$(id).value=active[key]||'';$('admin-images').value=(active.images||[]).join('\n');$('admin-published').checked=active.published!==false;$('admin-featured').checked=active.featured===true;}
function list(){const term=$('admin-search').value.toLowerCase(),selected=$('admin-product').value;const products=all().filter(p=>`${p.id} ${p.name}`.toLowerCase().includes(term));$('admin-product').replaceChildren(...products.map(p=>new Option(`${p.id} · ${p.name}${p.published===false?' · borrador':''}`,p.id)));if(products.some(p=>String(p.id)===selected))$('admin-product').value=selected;if(products.length)loadProduct($('admin-product').value);$('admin-product-form').hidden=!products.length;}
function safe(fn){try{fn();}catch(e){status(e.message);}}
$('admin-search').addEventListener('input',list);$('admin-product').addEventListener('change',e=>loadProduct(e.target.value));$('admin-category').addEventListener('change',()=>{$('admin-topic').disabled=$('admin-category').value!=='urbano';});
$('admin-product-form').addEventListener('submit',e=>{e.preventDefault();safe(()=>{if(!active)return;const next=structuredClone(data),p={name:$('admin-name').value.trim(),img:$('admin-main-image').value.trim(),price:Number($('admin-price').value),category:$('admin-category').value,published:$('admin-published').checked,featured:$('admin-featured').checked,stock:{},description:$('admin-description').value.trim(),leadTime:$('admin-lead').value.trim(),images:$('admin-images').value.split('\n').map(s=>s.trim()).filter(Boolean)};for(const size of ['S','M','L'])p.stock[size]=Number($('admin-stock-'+size).value);if(p.category==='urbano')p.subcategory=$('admin-topic').value;next.products[active.id]=p;commit(next,'Producto actualizado');list();});});
$('admin-new-form').addEventListener('submit',e=>{e.preventDefault();safe(()=>{const next=structuredClone(data),id=Math.max(3999,...all().map(p=>p.id))+1,stock=Number($('new-stock').value);next.newProducts.push({id,name:$('new-name').value.trim(),price:Number($('new-price').value),category:$('new-category').value,garment:$('new-garment').value,img:$('new-image').value.trim(),stock:{S:stock,M:stock,L:stock},published:false});commit(next,'Producto creado como borrador');$('admin-search').value='';list();$('admin-product').value=id;loadProduct(id);e.target.reset();});});
$('admin-category-form').addEventListener('submit',e=>{e.preventDefault();safe(()=>{const next=structuredClone(data);next.categories[$('category-key').value]=$('category-name').value.trim();commit(next,'Categoría guardada');options();list();});});
$('admin-default-lead').value=data.leadTime||'';$('admin-save-lead').addEventListener('click',()=>safe(()=>{const next=structuredClone(data);next.leadTime=$('admin-default-lead').value.trim();commit(next,'Plazo guardado');}));
function guide(){const rows=data.sizeGuides[$('guide-garment').value]||[];$('guide-fields').replaceChildren();for(const size of ['S','M','L']){const row=document.createElement('div');row.className='fields';for(const [field,label]of [['widthCm','Ancho'],['lengthCm','Largo']]){const l=document.createElement('label');l.textContent=`${size} · ${label} (cm)`;const input=document.createElement('input');input.id=`guide-${size}-${field}`;input.type='number';input.min='1';input.max='200';input.step='.1';input.value=rows.find(r=>r.size===size)?.[field]||'';l.append(input);row.append(l);}$('guide-fields').append(row);}}
$('guide-garment').addEventListener('change',guide);$('admin-save-guide').addEventListener('click',()=>safe(()=>{const next=structuredClone(data),rows=[];for(const size of ['S','M','L']){const w=$(`guide-${size}-widthCm`).value,h=$(`guide-${size}-lengthCm`).value;if(w||h)rows.push({size,widthCm:Number(w),lengthCm:Number(h)});}next.sizeGuides[$('guide-garment').value]=rows;commit(next,'Medidas guardadas');}));
function contentLists(){for(const [type,target]of [['gallery','gallery-list'],['reviews','review-list']]){$(target).replaceChildren();data[type].forEach((entry,i)=>{const row=document.createElement('div');row.className='admin-entry';row.textContent=entry.title||`${entry.name}: ${entry.text}`;const b=document.createElement('button');b.type='button';b.textContent='Retirar';b.onclick=()=>safe(()=>{const next=structuredClone(data);next[type].splice(i,1);commit(next,'Contenido retirado');contentLists();});row.append(b);$(target).append(row);});}}
$('admin-gallery-form').addEventListener('submit',e=>{e.preventDefault();safe(()=>{const next=structuredClone(data);next.gallery.push({title:$('gallery-title').value.trim(),image:$('gallery-image').value.trim(),consent:$('gallery-consent').checked});commit(next,'Trabajo agregado');contentLists();e.target.reset();});});
$('admin-review-form').addEventListener('submit',e=>{e.preventDefault();safe(()=>{const next=structuredClone(data);next.reviews.push({name:$('review-name').value.trim(),text:$('review-text').value.trim(),consent:$('review-consent').checked,verified:$('review-verified').checked});commit(next,'Opinión agregada');contentLists();e.target.reset();});});
function download(text,name,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),30000);}
$('admin-export').addEventListener('click',()=>safe(()=>{core.validate(data);download('/* Exportado desde Momotus Core */\nglobalThis.MomotusStoreConfig = '+JSON.stringify(data,null,2)+';\n','configuracion.js','text/javascript');status('Configuración exportada. Reemplazá tienda/js/configuracion.js al publicar.');}));
$('admin-backup').addEventListener('click',()=>download(JSON.stringify(data,null,2),'momotus-catalogo-respaldo.json','application/json'));
$('admin-import').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>2*1024*1024)throw Error('Máximo 2 MB por configuración.');const parsed=JSON.parse(await file.text());const next={...core.blank(),...parsed};commit(next,'Respaldo importado');options();list();guide();contentLists();$('admin-default-lead').value=data.leadTime||'';}catch(error){status('No se pudo importar: '+error.message);}});
options();list();guide();contentLists();
})();
